const { GoogleGenAI, Type } = require("@google/genai");

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });

const systemInstruction =
    "You are an expert tech writer for a blog that covers the latest tech news trends AI developments and productivity hacks ";
async function generatePost() {
    let contents = 'Use the most trending tech news from the last 24 hours to generate a blog post in JSON format {"title":"","description":"","category":""/*randomly choose from artificial intelligence technology digital marketing productivity*/,"content":"","tags":[],"imageUrl":""} where "title" is irresistible and clickable "description" is tweet-friendly with FOMO "content" is written using only semantic HTML elements like h1 h2 p ul li no style head or body tags, dont include the post title in the content, "tags" includes relevant SEO terms and "imageUrl" is a landscape image link that visually represents the news generated by the model with dimensions 600x400'
    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents,
        config: {
            systemInstruction
        }
    });
    console.log("generated post", response.text);

    let cleanText = response.text.replace(/```json|```|\*/g, "");
    let formatJson = JSON.parse(cleanText);
    return formatJson;
}

module.exports = generatePost;
